### ISSUE TITLE
AmplitudeClient.UpdateServer crash

### ISSUE THREAD

**Issue by ipereziriarte** [amplitude/Amplitude-Android#103]
Hi!

Reviewing my production app logs I've found a weird crash when Amplitude calls to **UpdateServer.**
It's quite weird, because it only happens to one device model but I'm scared about that the carrier starts to promote that device and becomes popular in the country.  

There's no way I can run and debug on this device, it's restricted to Turkey  

### Environment

+ Amplitude version **2.3.0**
+ Affected environment: **production**
+ Android version: **Android 4.4.2**
+ Device: **casper_via_v8 (only)**

### StackTrace

```
Fatal Exception: java.lang.NoSuchFieldError: byte.
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:798)
       at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:778)
       at com.amplitude.api.AmplitudeClient$7.run(AmplitudeClient.java:772)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Many thanks for your support

**Comment by djih** [comment]
@ipereziriarte thanks for reporting this. I noticed that you are using v2.3.0 of our SDK. The latest version is v2.7.1, and we've patched quite a few bugs since then. Maybe try updating to the latest version and seeing if the crash still occurs?

**Comment by ipereziriarte** [comment]
@djih you're right. I'll upgrade to the latest version for this week release and come back as soon as I get feedback from our users.
Thanks!

**Comment by ipereziriarte** [comment]
@djih I've updated to v2.7.1 and the crash is not happening anymore. You can close this issue :)
Thanks for your support

**Comment by djih** [comment]
@ipereziriarte that's great, glad it's fixed. now to patch your other crash
