### ISSUE TITLE
Runtime exception for the first-time amplitude use

### ISSUE THREAD

**Issue by StarWindMoonCloud** [amplitude/Amplitude-Android#105]
By following the instruction: https://github.com/amplitude/Amplitude-Android, could someone help check?

Exception as below:
05-19 18:20:54.737 28360-28360/com.haiqili.msgads E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.haiqili.msgads, PID: 28360
                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amplitude/api/Amplitude;

Gradle file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.haiqili.msgads"
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.amplitude:android-sdk:2.7.1'
}

**Comment by djih** [comment]
@StarWindMoonCloud , the gradle file looks right to me. Do you have any special proguard rules? Did you sync gradle files? Did you do `import com.amplitude.api.Amplitude;` ?
