### ISSUE TITLE
Nested JSONObject inside event_properties got flatten

### ISSUE THREAD

**Issue by eminge** [amplitude/Amplitude-Android#130]
Hi! We're using Amplitude in our application and when trying to add a JSONObject inside "event_properties" it's represented like that:
```
"event_properties": {
    "nested_obj.key1": "value1",
    "nested_obj.key2": value2,
    "nested_obj.key3": value3,
    …… 
}
```
while we're expecting it to be:
```
"event_properties": {
    "nested_obj": {
        "key1": "value1",
        "key2": value2,
        "key3": value3,
    },
    …… 
}
```
So I wonder where the first representation came from?!

Thanks!

**Comment by djih** [comment]
Hi @eminge , we allow 1 level of nesting in event_properties, but we flatten the properties server-side after the SDK uploads the events, resulting in the format that you are seeing

**Comment by eminge** [comment]
Hi @djih, Thanks for letting me know! But is there any plans to allow multiple nested level? Or can we ask for it as a feature request?
Thanks!

**Comment by djih** [comment]
@eminge unfortunately we currently do not have any plans to add support for it. What is your use case for it? Say we did add support for it, what kind of queries would you run on the data?

**Comment by eminge** [comment]
@djih it's more about parsing the raw events as sometimes we have nested list of JSONObjects or a single nested JSONObject inside event_properties and in this case we need to handle the single nested objects differently by looking on the common prefix or something, while in the list of JSONObjects we know that it's well formatted
