### ISSUE TITLE
ConcurrentModificationException in AmplitudeClient#setUserProperties(JSONObject)

### ISSUE THREAD

**Issue by scottkennedy** [amplitude/Amplitude-Android#138]
https://github.com/amplitude/Amplitude-Android/blob/40d82e77e1221187a32d5a2ce94e1a802167ad8d/src/com/amplitude/api/AmplitudeClient.java#L1309

`userProperties.toString()` is throwing an Exception because our code is concurrently modifying it, which is a little ironic, given the comment explaining the reason for copying it.

In our app, most things run on the main thread, which means cloning this object on a different thread exposes this problem for us.  As a result, we're now having to call `mAmplitudeClient.setUserProperties(new JSONObject(userProperties.toString()));`.

If you moved the copying off the log thread and onto whatever thread called `#setUserProperties()`, this would at least be more intuitive to the caller.

**Comment by djih** [comment]
@scottkennedy we will patch this in our next version which we are releasing today

**Comment by djih** [comment]
@scottkennedy this is fixed with [v2.13.4](https://github.com/amplitude/Amplitude-Android/releases/tag/v2.13.4), should be available on Maven within an hour or so
