### ISSUE TITLE
2.14.0: Amplitude.getInstance() is broken in unit tests

### ISSUE THREAD

**Issue by autonomousapps** [amplitude/Amplitude-Android#146]
Because `TextUtils.isEmpty()` is part of the Android SDK, and so always returns `false`. If you call the default `Amplitude.getInstance()` method (which worked fine for 2.13.4), it passes `null` to the `normalizeInstance()` method. Therefore, `instance` is always `null` at line 98 when you try to call `instance.toLowerCase()`.

**Preferred resolution:** don't use Android SDK methods if they are not necessary. Use your own `StringUtils.isEmpty()` method (or whatever).

There is a workaround, to use `Amplitude.getInstance(String)`, but clients must take care to use lowercase strings, because the `normalizeInstance()` method simply won't behave correctly in a unit-testing context. Since this leaks implementation details that clients shouldn't have to care about, I consider this a bug.

I am also not clear on the consequences of having a 'named' instance of Amplitude. Is there really call for multiple instances?

**Comment by djih** [comment]
@autonomousapps I'm not sure I follow, can you elaborate around unit tests and TextUtils.isEmpty returning false? We have many unit tests for our Android SDK, these here specifically test the multiple instance logic: https://github.com/amplitude/Amplitude-Android/blob/master/test/com/amplitude/api/AmplitudeTest.java, and the tests do pass.

In terms of multiple instances, it's a feature our other 2 SDKS (iOS / JS) already have, we are just reaching feature parity with the Android SDK. It's a feature that a lot of our customers have been asking for

**Comment by autonomousapps** [comment]
That's because you're using Robolectric in all your unit tests. We are not.

From your perspective, I can see why you might want to just answer "well, start using it." However, since the "fix" is so simple (removing usage of `TextUtils`, which is part of the Android SDK and just doing `if (instance == null || instance.isEmpty())`, I think you should fix it :) Also, putting an implicit requirement on your users to test in a particular way seems not-so-good to me.

**Comment by djih** [comment]
@autonomousapps I wouldn't consider this a bug in our SDK since we are using a standard Android library method the way it was intended. The unfortunate side effect is that those methods return false in certain test environments, but that seems to be a known issue with Android. Wouldn't this be an issue with any library or any piece of code that uses Android libraries?

Is it possible for you guys to not use default return values in your unit tests (like in: https://stackoverflow.com/questions/39862072/textutils-isemptynull-returns-false)? Alternatively, could you mock out TextUtils which seems to be what the Android documentation suggests (https://developer.android.com/training/testing/unit-testing/local-unit-tests.html)?

I don't want to release a new version of our Android SDK that just reimplements the same logic.

**Comment by autonomousapps** [comment]
I humbly suggest we should follow the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Why use a method that'll (a) break on a standard unit test or (b) require that test to be written in a particular way, especially when there's a very easy, low-friction way to avoid that? I think the burden is on the library author (you) to make life easier for your clients, not on clients (me) to make life easier for you.

To your first suggestion: we do that, but the default for boolean is `false`. Even if the default were `true`, that hardly improves matters. To your second suggestion, I have no idea how to "mock out" static methods in `TextUtils` absent the use of something like PowerMock, which brings me back to point (b) in my first paragraph.

**Comment by autonomousapps** [comment]
...although, to be fair, Android development, especially in the context of testing, often feels like it follows a "principle of greatest astonishment."

**Comment by djih** [comment]
@autonomousapps I have a branch with the changes: https://github.com/amplitude/Amplitude-Android/pull/147/files. Feel free to review and test. I have rebuilt the SDK jars so you can download them and test against your unit tests. If it looks good, I can merge and release a patch version

Link to rebuilt Jars:
With dependencies (Okhttp3): https://github.com/amplitude/Amplitude-Android/raw/54cfba195daabefa8f16a9fe74cd57bc9a2861f9/amplitude-android-2.14.0-with-dependencies.jar

Without dependencies: https://github.com/amplitude/Amplitude-Android/raw/54cfba195daabefa8f16a9fe74cd57bc9a2861f9/amplitude-android-2.14.0.jar

**Comment by autonomousapps** [comment]
Thank you! I will test soon.

**Comment by autonomousapps** [comment]
Yes, it works! For the record, I used the "without dependencies" version. We use OkHttp3 in our project and I wasn't sure about dependency conflicts.

**Comment by djih** [comment]
Yea that's fine, the with dependencies version is for people who aren't using OkHttp3. Thanks for testing, expect a new version out by EOD tomorrow, will keep you updated

**Comment by djih** [comment]
@autonomousapps we have released v2.14.1: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.14.1. It should show up in Maven within an hour or so.
