### ISSUE TITLE
How to track session if a custom ActivityLifecycleCallbacks implementation is already registered

### ISSUE THREAD

**Issue by rishabh876** [amplitude/Amplitude-Android#178]
We already have a custom `ActivityLifecycleCallbacks` implementation registered in our application. In the documentation, I am unable to find a way to accommodate Amplitude's Session Tracking in our app. Usually there are public functions that can be called in such cases like `amplitudeClient.onPause()` and  `amplitudeClient.onResume()` from custom `ActivityLifecycleCallbacks` implementation. But I couldn't find any such workaround for this as well. 
How can I track session in this case?

**Comment by dantetam** [comment]
For you, and anyone else who is interested, we have a guide for this: https://developers.amplitude.com/docs/android#user-sessions
