### ISSUE TITLE
Make Server URL configurable

### ISSUE THREAD

**Issue by doncung** [amplitude/Amplitude-Android#179]
We have a use case of passing our data to another server before sending to Amplitude. This is to perform  any filtering on the data necessary for security or legal reasons.
As such is it possible to either make EVENT_LOG_URL non final or reference it as a protected method or variable in AmplitudeClient.

**Comment by djih** [comment]
@doncung  sorry forgot to follow up, we added a `setServerUrl` method since v2.22.0 (https://github.com/amplitude/Amplitude-Android/releases/tag/v2.22.0)
