### ISSUE TITLE
A lot of devices have "None" device type

### ISSUE THREAD

**Issue by Stasssm** [amplitude/Amplitude-Android#192]
In our Amplitude reports we can see that the most of devices have "None" type. Can you tell the possible reasons for this? Is it possible to fix it?

<img width="1351" alt="BugAmplitude" src="https://user-images.githubusercontent.com/4447037/54109825-c9e5bf80-43f0-11e9-806a-3346325397ab.png">

**Comment by djih** [comment]
@Stasssm this is because of new android devices that came out that haven't yet been added to our device mapping. You can notify your CSM or platform to update it
