### ISSUE TITLE
Events aren't tracked, too_many_requests error

### ISSUE THREAD

**Issue by HuascarBaptista** [amplitude/Amplitude-Android#196]
Hi, 

Tracking an event the first time works fine, but after that, it doesn't work again, the logcat shows me `com.amplitude.api.AmplitudeClient: Upload failed, too_many_requests, will attempt to reupload later`

I tried with 3 devices, the same and only event, and in two of those, I got the same failed answer.

Devices: 
1) Samsung S8 API 28 - failed 
2) Emulator Nexus 5X API 28 - failed 
3) Moto G6 API 27 - success 

I already tried cleaning cache, cleaning data, and I got the same error even it is not trying to reupload the event.

The code response that I am getting is 429.

Could you help me, please? Thanks.

**Comment by djih** [comment]
@HuascarBaptista that just means that you're tracking events too quickly for a single user. See the 429 section in our help article: https://help.amplitude.com/hc/en-us/articles/204771828-HTTP-API#http-status-codes-retrying-failed-requests. But don't worry the SDK stores all unsent events on each device and will try again until the events all upload. After a minute the user's send rate will drop, and the next batch of events will get through, etc.
