### ISSUE TITLE
NullPointerException when setting ID (possibly with wrong input)

### ISSUE THREAD

**Issue by superphil0** [amplitude/Amplitude-Android#201]
Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke virtual method 'int java.lang.String.length()' on a null object reference Raw Text
--
  | org.json.JSONTokener.nextCleanInternal + 116 (JSONTokener.java:116)
  | org.json.JSONTokener.nextValue + 94 (JSONTokener.java:94)
  | org.json.JSONObject.<init> + 159 (JSONObject.java:159)
  | org.json.JSONObject.<init> + 176 (JSONObject.java:176)
  | com.amplitude.api.DatabaseHelper.getEventsFromTable + 253 (DatabaseHelper.java:253)
  | com.amplitude.api.DatabaseHelper.getEvents + 231 (DatabaseHelper.java:231)
  | com.amplitude.api.AmplitudeClient.updateServer + 1522 (AmplitudeClient.java:1522)
  | com.amplitude.api.AmplitudeClient.updateServer + 1494 (AmplitudeClient.java:1494)
  | com.amplitude.api.AmplitudeClient$13.run + 1485 (AmplitudeClient.java:1485)
  | android.os.Handler.handleCallback + 789 (Handler.java:789)
  | android.os.Handler.dispatchMessage + 98 (Handler.java:98)
  | android.os.Looper.loop + 164 (Looper.java:164)
  | android.os.HandlerThread.run + 65 (HandlerThread.java:65)

I think this error should be caught, currently it crashes android application

**Comment by superphil0** [comment]
not sure if this belongs here this happens when using  https://github.com/expo/expo/tree/master/packages/expo-analytics-amplitude

which uses 2.9.2 of this lib

**Comment by haoliu-amp** [comment]
@superphil0 So you are using this library instead of using our native library? However, we do need to add try/catch around it.

**Comment by superphil0** [comment]
I think this was because expo-analytics-amplitude was using an old version, they upgraded now and it is fixed, you can close this issue

**Comment by haoliu-amp** [comment]
@superphil0 Thanks!
