### ISSUE TITLE
ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION should not be required

### ISSUE THREAD

**Issue by shaunpanjabi** [amplitude/Amplitude-Android#236]
I just added this SDK and noticed it required these permissions. I understand that you use the location manager, however this functionality doesn't even work unless you get explicit permission from the user. 

I think these should be removed from the AndroidManifest, and location listening should be off by default since it won't work anyway unless your app needs location and prompts the user.

**Comment by 5upernaut** [comment]
Any news on this? We can't upgrade Amplitude anymore, as we won't be asking our users to allow these permissions.

**Comment by haoliu-amp** [comment]
Hey all, today I pushed a new version 2.25.1. 
https://github.com/amplitude/Amplitude-Android/releases/tag/v2.25.1

It should be available in maven repo within 1-3 days.
