### ISSUE TITLE
deviceType tracking is not accurate

### ISSUE THREAD

**Issue by mishra-himanshu** [amplitude/Amplitude-Android#244]
Hi,

We were looking at the number of users using android tablets in amplitude and the numbers are very high compared to mobile users.
This doesn't seem accurate. 
As per the API docs https://developers.amplitude.com/docs/http-api-v2#footnotes

> Amplitude will attempt to use device_brand, device_manufacturer, and device_model to map the corresponding device type.

Is there a way to check what devices are qualifying as tablets for deviceType attribute?

**Comment by haoliu-amp** [comment]
Hey, wonder how did you create the query for comparing the numbers between tablets and phones?

e.g. "device family" contains "tablet"??

We might need to share some private info that might help us further investigate. So feel free to file a ticket [here](https://help.amplitude.com/hc/en-us/requests/new)

**Comment by mishra-himanshu** [comment]
Hi, I am looking at deviceDetails.deviceType attribute.
Create a ticket request#43511

Thanks
