### ISSUE TITLE
isLimitAdTrackingEnabled check not required.

### ISSUE THREAD

**Issue by pqvst** [amplitude/Amplitude-Android#25]
After some digging I noticed that the SDK checks "isLimitAdTrackingEnabled" when fetching the advertising ID. This check "could" be removed (or at least provide an override).

> Respecting users' selections. Upon reset, a new advertising identifier must not be connected to a previous advertising identifier or data derived from a previous advertising identifier without the explicit consent of the user. Furthermore, you must abide by a user’s “opt out of interest-based advertising” setting. If a user has enabled this setting, you may not use the advertising identifier for creating user profiles for advertising purposes or for targeting users with interest-based advertising. **Allowed activities include contextual advertising, frequency capping, conversion tracking, reporting and security and fraud detection.**

http://stackoverflow.com/a/20358978/966782

**Comment by djih** [comment]
thanks for the info @pqvst
