### ISSUE TITLE
iOS and JavaScript have setSessionId methods, but Android does not.

### ISSUE THREAD

**Issue by msquitieri** [amplitude/Amplitude-Android#252]
Your iOS SDK supports the setSessionId method:

- http://amplitude.github.io/Amplitude-iOS/Classes/Amplitude.html#//api/name/setSessionId:

Your JavaScript SDK supports a setSessionId method:

- https://github.com/amplitude/Amplitude-JavaScript/blob/master/src/amplitude-client.js#L932

What can I use in order to set the session ID from the Android SDK?

**Comment by msquitieri** [comment]
Should I be using the `startOrContinueSession` method instead?

**Comment by dantetam** [comment]
Hello @msquitieri , sorry for the late reply. Very good question.

Out of posterity for the next developers using Amplitude, you should use the public exposed API
`public boolean startNewSessionIfNeeded(long timestamp)` in `AmplitudeClient.java`. For now, this is the intended use of the product for Android as this method has some extra checks related to Android.

Thanks,
Dante
