### ISSUE TITLE
Use ads-identifier library instead of play-services-ads to fetch advertising ID

### ISSUE THREAD

**Issue by ubuntudroid** [amplitude/Amplitude-Android#255]
## Summary

Right now the SDK uses the big `play-services-ads` library to fetch the advertising ID. However, Google has introduced the much smaller and better scoped `ads-identifier` library for exactly that task: https://developer.android.com/training/articles/ad-id

## Motivations

The new Advertising ID library is smaller and better scoped. Especially apps which don't already display Google Ads would benefit from switching to the Advertising ID library. Also, using the new library now is Google's recommended approach to fetch the Advertising ID on Android.

**Comment by haoliu-amp** [comment]
@ubuntudroid This's a really good point! We will take a look.

**Comment by ubuntudroid** [comment]
Any news here? :-)

**Comment by dantetam** [comment]
Hello @ubuntudroid, sorry for the delay. I appreciate you pointing this out and I did actually test your proposed change with our Android SDK.

My concern is that much of our Android SDK code is already built around Google Play Services. Our automated tests and even our other SDKs (React Native and Unity) use this codebase. I cannot justify the risk to Amplitude's day-to-day operation to save a few megabytes in Gradle dependencies. It's the same reason we don't migrate to Java 11. In your proposal I believe you are referring to Firebase AdMob SDK; the migration to this platform would be its own new story and a product consideration I would discuss with my peers.

Please reach out, this was a very informative concern. If there's no more new info I will close the ticket.

**Comment by ubuntudroid** [comment]
I'm not proposing moving away from play services, just from `play-services-ads` to the much leaner (also official) `ads-identifier` [library](https://developer.android.com/jetpack/androidx/releases/ads) which now seems to be the preferred way to get the ad identifier. From what I saw getting the identifier ist the only thing for what `play-services-ads` is used in the amplitude SDK, so the changes should be minimal and would not affect other areas of the SDK.

Please note, that the `ads-identifier` library doesn't have anything to do with Firebase or Firebase AdMob SDK, in fact its dependency shows, that it comes from the androidx cluster of libraries:

```groovy
implementation 'androidx.ads:ads-identifier:1.0.0-alpha04' // please note, that alpha04 is the most recent version, while the docs still refer to alpha01
```

The only concern would be, that this is still in alpha - however, given that it is already suggested in the official Android developer guidelines, it should be safe to use. Linking the [relevant section here](https://developer.android.com/training/articles/ad-id) once more for reference.

**Comment by dantetam** [comment]
My bad. I ran into a combination of strange Gradle dependency issues and misread your proposal. I did investigate and yeah, it looks like `AdvertisingIdClient` is the only actual library class we are using. I ran into some other deprecated libraries like `com.google.android.gms.common.GooglePlayServicesUtil` that I'll investigate more into. I've seen the new package you are referring to in `androidx...` and I'll be testing that again.

**Comment by dantetam** [comment]
Running into issues integrating the Androidx module:

1) `AdvertisingIdClient.isAdvertisingIdProviderAvailable(context)` returns false

2) `androidx.ads.identifier.advertisingidnotavailableexception: no compatible androidx advertising id provider available.`

Both these errors are widely reported:

[stackoverflow 1](https://stackoverflow.com/questions/57534206/can-not-get-advertising-id-provider-in-android)

[stackoverflow 2](https://stackoverflow.com/questions/64087871/how-to-get-google-ad-id-in-android-java)

[google issuetracker](https://issuetracker.google.com/issues/155937847)

I was able to retrieve (from real life Android phone as well as an emulator) advertiser IDs using the current package `com.google.android.gms:play-services-ads`. If this library reliably works, we could save 4 MB (36MB → 32MB) in dependencies. Note this library has no general releases, only alphas (`androidx.ads:ads-identifier:1.0.0-alpha04`). 

If anyone is interested in reproducing these errors, `git clone --single-branch --branch androidxtest https://github.com/dantetam/Amplitude-Android`

**Comment by ubuntudroid** [comment]
Unfortunately this is getting worse now as with version 21.4.0 the admob SDK now requires setting an admob app ID in the manifest. As we are just using the SDK to pull the advertising ID most apps won't have such an ID.

For now this means staying at version 21.3.0 and not updating, but going forward this will become more and more of a problem with APIs used in that version getting deprecated and in the worst case eventually shut down. 😔

Here is the crash that is thrown at app start when attempting to use 21.4.0 without setting an app ID:

```
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
                 
                 ******************************************************************************
                 * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
                 * should follow the instructions here:                                       *
                 * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
                 * to add a valid App ID inside the AndroidManifest.                          *
                 * Google Ad Manager publishers should follow instructions here:              *
                 * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
                 ******************************************************************************
```

**Comment by ubuntudroid** [comment]
@dantetam any news here? I could not update AdMob anymore for half a year now because of the abovementioned issue. 😢

**Comment by ubuntudroid** [comment]
@dantetam @haoliu-amp Bumping this one once more as it really is becoming a problem for everyone using Admob - which is every Amplitude SDK Android client app.
