### ISSUE TITLE
How to log event property with empty value?

### ISSUE THREAD

**Issue by matsoab** [amplitude/Amplitude-Android#263]
## Summary
`Amplitude.getInstance(instanceName).logEvent("SomeEvent", withEventProperties: ["SomeKey": ""])`
works like "event with not properties" and there is no info about avoiding passing empty strings as values in the official documentation.
Is there an official way to post empty string (or other empty value) to amplitude? Or maybe is it a bug?

**Comment by dantetam** [comment]
Hello @matsoab ,

This is an insightful question and I'm sorry for the delay in getting back to you. 

I just tested this myself and can confirm, empty strings do not show up in event properties. We are actively working now to improve our documentation, and this is helpful for specific Android SDK questions. I will update that for now.

Yes, I can imagine use cases in which one may wish to pass empty strings. I will discuss with the team, as I am not sure if this is intended behavior or simply not a feature.

Thanks,
Dante

**Comment by rodrigovidelauala** [comment]
Hello @dantetam  ,

Was this updated in the documentation? I can't find it. Could you please provide me a link?
