### ISSUE TITLE
How to rewrite default user properties?

### ISSUE THREAD

**Issue by dmersiyanov** [amplitude/Amplitude-Android#266]
## Rewriting default user properties
SDK version - 2.30.1

So I would live to rewrite the value of the default user property Version. 
It's mentioned here in docs - https://help.amplitude.com/hc/en-us/articles/115002380567-User-Properties-Event-Properties and https://help.amplitude.com/hc/en-us/articles/215562387-Appendix-Amplitude-User-Property-Definitions.

Let's use this [event ](https://analytics.amplitude.com/dpdrussia/project/294323/search/amplitude_id%3D202859852906?sessionHandle=XfZcF1R_XfZcF1R_C87Y7Rq_BH2z_30733ad3-296e-4f7e-9118-e8f4bce1b07bR&eventId=5340c198-7771-11eb-93c7-025b773acf41 )as an example:

1) pic [#1](https://pasteboard.co/JQTNQwq.jpg) - the default Version user property is highlighted
2) pic [#2](https://pasteboard.co/JQTO4yO.jpg) - my custom Version user property is highlighted
3) pic [#3](https://pasteboard.co/JQTOdP7.jpg) - here I've highlighted two properties with the same name "version_name" but the first one is set by me by the following code:

`fun setUserProperty() {
    val identify = Identify()
    identify.set("version_name", "1.5.0")
    amplitude.identify(identify)
}`

Is there a way to change the value of the default user property?

**Comment by dantetam** [comment]
Hello @dmersiyanov ,

Thank you for your question. We do not have an option to rewrite the default user properties, but you may turn off their tracking, and like you proposed, use a custom user property in your own analysis.

```
AmplitudeClient client = ...;
TrackingOptions trackingOptions = new TrackingOptions();
trackingOptions.disableVersionName();
client.setTrackingOptions(trackingOptions);
```

I appreciate the question as we are currently working on the documentation.

Dante
