### ISSUE TITLE
How to enable Event Explorer?

### ISSUE THREAD

**Issue by boneqedo** [amplitude/Amplitude-Android#267]
I want to enable Event Explorer for my project, but unfortunately, I can't do this, as this functionality depends on the BuildConfig.DEBUG flag, which is always false for the library from maven:

https://github.com/amplitude/Amplitude-Android/blob/40c12e9e017e2cc633b7383c1b032fcf1f04caf0/src/main/java/com/amplitude/api/AmplitudeClient.java#L780-L787

It would be nice to know, is this intended behavior or a bug?

**Comment by dantetam** [comment]
Hello @boneqedo ,

Thank you for calling this out. This is definitely not an intended feature. Will fix soon.

Will close after the change is made and the release comes out

Dante

**Comment by boneqedo** [comment]
Hello @dantetam,

Ok, got it, thanks for the information!
I'm looking forward to it.

**Comment by dantetam** [comment]
Hello again @boneqedo ,

This issue was fixed in v2.30.2.

Dante
