### ISSUE TITLE
Revenue [verified] event doesn't appear on Amazon device

### ISSUE THREAD

**Issue by kkarunakaran** [amplitude/Amplitude-Android#272]
## Expected Behavior
Revenue [verified] event appears

## Current Behavior
Only Revenue event shows up

## Steps to Reproduce
1. Make a live testing purchase on Amazon fire HD device
2. Tigger an iap event 

**Sample**
Receipt
{"receiptId":"7ScSG2szT5w1BZPK96qE_Cw2iqxySSeg7uVMSVOu1pY=:1:12", "itemType":"CONSUMABLE", "purchaseDate":"Tue Mar 23 13:08:05 GMT-04:00 2021", "sku":"com.budgestudios.UnityIAP.Consumable2.A"}

Receipt SigRevenue
KbQOplsthESb_PSIxBlCV4vhUkxumfBCdRQTTJL4iCg=

**Direct request to amazon end point works though** 
https://appstore-sdk.amazon.com/version/1.0/verifyReceiptId/developer/{dev_secret}/user/KbQOplsthESb_PSIxBlCV4vhUkxumfBCdRQTTJL4iCg=/receiptId/7ScSG2szT5w1BZPK96qE_Cw2iqxySSeg7uVMSVOu1pY=:1:12

## Environment
- SDK Version: com.amplitude.android-sdk-2.27.0
- Android API Level: 5.1.1
- Device: Amazon fire HD 

![2940a3b7-193c-43fd-ab2e-a157f87fc4c6](https://user-images.githubusercontent.com/57362013/112252657-e9489180-8c33-11eb-8b61-e38338fe393c.png)

**Comment by dantetam** [comment]
Thank you the detailed bug report @kkarunakaran, I will take a look into this.

**Comment by dantetam** [comment]
I received this ticket through our Platform Specialists, who clarified this was a call through Unity SDK. 

Was the Amplitude project set up for Amazon Store revenue verification?
From our documentation: 

> For purchases on the Amazon store, you should copy your Amazon Developer Shared Secret into the Sources & Destinations section of your project in Amplitude. After a successful purchase transaction, you should send the purchase token as the ‘receipt’ and the User ID as the ‘receiptSignature’:

**Comment by kkarunakaran** [comment]
Hello @danteta. Thanks for the reply. I already have the dev secret added. 

<img width="1683" alt="Screen Shot 2021-03-25 at 10 11 50 PM" src="https://user-images.githubusercontent.com/57362013/112567531-5cc6dc00-8db7-11eb-8c50-237132c5a47a.png">

Tried triggering another event today. 

<img width="1707" alt="image" src="https://user-images.githubusercontent.com/57362013/112567695-af07fd00-8db7-11eb-81aa-bb29f3e93dbd.png">

**UserID** 
77aee9fc-1923-4b7a-a6f0-bb9e99ad6e46

**AmplitudeID**
245364049876

**ReceiptId**
{"receiptId":"1KcBiqpwH79gAPpyEToVLfAjPf8CWsSzmVC5ava6ePw=:3:12", "itemType":"SUBSCRIPTION", "purchaseDate":"Thu Mar 25 16:09:18 GMT-04:00 2021", "sku":"com.budgestudios.UnityIAP.Subscription2.A"}

**ReceiptSignature**
KbQOplsthESb_PSIxBlCV4vhUkxumfBCdRQTTJL4iCg=

**Comment by dantetam** [comment]
Hello @kkarunakaran ,

We are currently investigating your issue through our Data Ingestion team. Your SDK code is correct (it does not change whether you are verifying for iOS, Google, or Amazon store) and the tokens worked just fine with iOS and Google store.

Dante

**Comment by kkarunakaran** [comment]
Thanks to Amplitude team in helping to get this resolved. They fixed in their backend and we are able to see the Revenue Events verified on Amazon. Closing this issue.

**Comment by dantetam** [comment]
Just saw the update from Data Pipelines team, thank you for reporting this issue.
