### ISSUE TITLE
deviceId is null after call initialize()

### ISSUE THREAD

**Issue by krottv** [amplitude/Amplitude-Android#282]
## Expected Behavior
deviceId shouldn't be null or we need to have a callback to know when amplitude is initialized correctly.

## Current Behavior
Hi. For integration for other analytics tools I need to know amplitude deviceId. And it is null after Amplitude.initialize(...) call. But If I fetch deviceId after like a second after initialize call then it is non null. 

## Possible Solution
Make a delay before fetching deviceId, but the problem is that I don't know in advance how long the initialization will take.

## Steps to Reproduce
 

1. Amplitude.initialize(...) 
2. Amplitude.getInstance().deviceId == null

## Environment
- SDK Version: 2.31.0
- Android API Level: 29
- Device: Samsung Galaxy s9+

**Comment by krottv** [comment]
@dantetam 
As I see from the source code there are two solutions and they seem pretty easy: 1. initialize deviceId instantly in the caller thread. or 2. add a callback when initialization is finished.

**Comment by dantetam** [comment]
Hello @krottv , 

We're going to close this issue because it's stale. If you need a deterministic (i.e. 100% certain solution) for a device ID, feel free to wait a long time or generate a device ID yourself and set it using the method below:

```
/**
     * Sets a custom device id. <b>Note: only do this if you know what you are doing!</b>
     *
     * @param deviceId the device id
     * @return the AmplitudeClient
     */
    public AmplitudeClient setDeviceId(final String deviceId) { ... }
```

**Comment by dantetam** [comment]
Hello @krottv and anyone else listening,

We plan to take this on very soon. Same for iOS. Thank you for the input.

**Comment by krottv** [comment]
@dantetam Nice.
The usecase is following. Inside the app I use Adapty - subscription management service which integrates with Amplitude. And in order to make integration, I need to pass amplitude.deviceId to Adapty. Here's docs for more info - https://doc.adapty.io/docs/amplitude

**Comment by dantetam** [comment]
Sorry for the late delay on this @krottv . Are you by chance using any workarounds right now? Like just waiting for a while? We've created a feature request for this ticket

**Comment by krottv** [comment]
@dantetam Yes. I use delay(500)
