### ISSUE TITLE
EventExplorerInfoActivity crash

### ISSUE THREAD

**Issue by zenyagami** [amplitude/Amplitude-Android#299]
## Expected Behavior
Open EventExplorerInfoActivity

## Current Behavior
There is a crash when i click in the "Bubble" to open EventExplorerInfoActivity

## Possible Solution
seems that the EventExplorerInfoActivity.java is not added in the manifest, from amplitud i manually added to my project but this should be in the amplitude manifest

```
<activity
            android:name="com.amplitude.eventexplorer.EventExplorerInfoActivity"
            android:exported="true"
            android:screenOrientation="portrait"
            />
```

## Steps to Reproduce

1. install sdk
2. use `client.showEventExplorer(activity)`
3. click in the bubble
4.proof

## Environment
- SDK Version: 2.32.1
- Android API Level: android 12 RC
- Device: Pixel 3XL

**Comment by haoliu-amp** [comment]
Hello, It should be in your application's own manifest, because we don't assume every customer would want this.
