### ISSUE TITLE
Invoke set Identity multiple times

### ISSUE THREAD

**Issue by juliansuis** [amplitude/Amplitude-Android#307]
I'm using Identity().set() in a way that is being called multiple times even though the value is the same. Is that a problem?
If so, how could I avoid it?

**Comment by CROCDC** [comment]
oooo its a good question, i have a same problem in my project

**Comment by Mercy811** [comment]
Hi @juliansuis @CROCDC, thanks for using Amplitude. Are you still have this issue? Could you share more info about it?
- the code snippet you use 
- log of how identity().set() is called

**Comment by juliansuis** [comment]
Bro, it's been way too long, one year and a half later, I don't know.

**Comment by Mercy811** [comment]
Thanks for your reply @juliansuis. Close this thread as it's outdated.
