### ISSUE TITLE
Usage of weak crypto algorithms like MD5 in Amplitude-Android SDK

### ISSUE THREAD

**Issue by nidhi88** [amplitude/Amplitude-Android#314]
## Summary

Our Penetration testing team has identified usage of weak crypto algorithms like MD5 in Amplitude-Android SDK and logged security vulnerability. What are the plans to migrate to the latest crypto algorithms? Can you please migrate to the latest crypto algorithms to mitigate this?

Recommendation:
Utilize cryptographic hashing algorithms that are considered secure and advocated for in best practice recommendations. Guidance can be found [for Android](https://developer.android.com/guide/topics/security/cryptography) For more guidance on best practices in picking strong cryptography, please see OWASP's [Cryptographic Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html).

## Motivations

Security Vulnerability.

**Comment by nidhi88** [comment]
Hi @qingzhuozhen 
Can you please check this issue?

**Comment by qingzhuozhen** [comment]
Hi @nidhi88, thanks for raising this. The MD5 is used for our checksum field, actually, you don't need to worry about the security concern for that. We switched to a different endpoint in https://github.com/amplitude/Amplitude-Kotlin, and that doesn't include the MD5 cypto algorithm.

**Comment by nidhi88** [comment]
Thanks, @qingzhuozhen for the update.

**Comment by justin-fiedler** [comment]
MD5 usage has been removed in v2.39.6
