### ISSUE TITLE
cleaner interface with map instead of JSON objects?

### ISSUE THREAD

**Issue by mderazon** [amplitude/Amplitude-Android#32]
Instead of using JSON objects:
``` java
JSONObject eventProperties = new JSONObject();
try {
    eventProperties.put("KEY_GOES_HERE", "VALUE_GOES_HERE");
} catch (JSONException exception) {
}
Amplitude.logEvent("Sent Message", eventProperties);
```
Why not using Java's built in Map ? 

Much cleaner IMO and doesn't require exception handling ?
Could be a method overload to keep BC

**Comment by allanca** [comment]
Thanks for the suggestion! I played with this a bit and found that some exception handling is still required unless we squelch all conversion exceptions down in the SDK. That's going to introduce subtle bugs and make it harder for devs to find issues early.

If that's the behavior you'd prefer, I suggest subclassing AmplitudeClient and adding a helper method.
