### ISSUE TITLE
Support Huawei with HMS CORE

### ISSUE THREAD

**Issue by Jparrgam** [amplitude/Amplitude-Android#328]
## Summary

Hi, 
amplitude sdk android has support for huawei cell phones that do not have GMS

**Comment by yuhao900914** [comment]
Hi @Jparrgam, 
Can you clarify your question?
Are you asking about if the amplitude-android has support for HMS CORE?

**Comment by Jparrgam** [comment]
hi @yuhao900914, amplitude-android support HMS CORE ? https://developer.huawei.com/consumer/en/hms/
