### ISSUE TITLE
Missing method in generated Ampli.kt

### ISSUE THREAD

**Issue by hamen** [amplitude/Amplitude-Android#331]
Hi all,

I'm experiencing some issue with the Ampli CLI.

## Expected Behavior

`ampli pull` would generate a working `Ampli.kt` file.

## Current Behavior

`ampli pull` generates an `Ampli.kt` containing:

```kotlin
open class Ampli {
    companion object {
        val API_KEY: Map<Environment, String> = mapOf(
            Environment.DEVELOPMENT to "SECRET",
            Environment.PRODUCTION to "SECRET"
        )

        private val observePlan: Plan = Plan()
            .setBranch("main")
            .setSource("android")
            .setVersion("22")
            .setVersionId("SECRET")
    }
[...]
```
where `setVersionId(..)` does not exist:

![image](https://user-images.githubusercontent.com/19003/162747017-dd169fe6-1174-4596-836f-dd58b6b3bea3.png)

## Steps to Reproduce
1. Run `ampli pull`
2. Try to build
3. Build fails.

## Environment
- SDK Version: @amplitude/ampli/1.6.0 wsl-x64 node-v12.22.12
- Android API Level: N/A
- Device: N/A

Thank you.

**Comment by justin-fiedler** [comment]
Hi @hamen,

Thanks for reaching out. The [setVersionId() method was added recently in Amplitude-Android 2.37.0](https://github.com/amplitude/Amplitude-Android/releases/tag/v2.37.0). Can you please check that you are using the latest version in your `build.gradle`?
`implementation 'com.amplitude:android-sdk:2.37.0'`

We include the minimum version of the underlying Amplitude-Android SDK required by Ampli in the header of Ampli.kt for reference.
https://github.com/amplitude/ampli-examples/blob/main/android/kotlin/AmpliApp/app/src/main/java/com/amplitude/ampli/Ampli.kt#L7

Hope this helps!

Justin

**Comment by justin-fiedler** [comment]
Hi @hamen, glad that fixed the issue!

>  I need to find a way to get notified when to bump the Amplitude version, due to Ampli update
We are looking into ways to improve this, I agree the minimum version to the generated code isn't the easiest to locate. We have a ticket in the backlog to show warning in the `ampli pull` output. I am interested if you have any other ideas for improvement. 

Thanks!

**Comment by hamen** [comment]
Hi @justin-fiedler 
I believe a ⚠️ message at the bottom of the `ampli pull` output would work smoothly 👍🏻
