### ISSUE TITLE
Amplitude stops tracking events when server zone is set

### ISSUE THREAD

**Issue by NuclearSnake** [amplitude/Amplitude-Android#341]
Hello!
Thank you for making a great lib for analytics better!

## Expected Behavior
Normal events tracking

## Current Behavior
Getting the "com.amplitude.api.AmplitudeClient: Invalid API key, make sure your API key is correct in initialize()" in logs; no events coming to the dashboard

## Steps to Reproduce
1. I have a simple test project where Amplitude works fine on v2
2. Then I add `.setServerZone(AmplitudeServerZone.EU)` and it doesn't track anymore
I tried two ways:
```
Amplitude.getInstance()
            .initialize(activity, "my api key goes here")
            .setServerZone(AmplitudeServerZone.EU)
            .enableForegroundTracking(activity.application)
```

and 

```
Amplitude.getInstance()
            .initialize(activity, "my api key goes here")
            .enableForegroundTracking(activity.application)
Amplitude.getInstance().setServerZone(AmplitudeServerZone.EU)
```

and also both ways but with `.setServerUrl("https://api.eu.amplitude.com")`

## Environment
- SDK Version: v.2.37.0, v.2.34.x, v3.35.1
- Android API Level: 7.1.2
- Device: Android Studio's Android Emulator

**Comment by NuclearSnake** [comment]
I noticed the latest version is 2.38.1 (not marked as the latest on the right on main lib page, but listed in text readme), and tried it too with the same result

**Comment by bohan-amplitude** [comment]
Hi @NuclearSnake , Thanks for using Amplitude. The project in EU zone amplitude website and project in US zone amplitude website have different API key. Could you check and make sure to use the API key from EU website project setting when sending events to EU API endpoint?

**Comment by NuclearSnake** [comment]
Hi, @bohan-amplitude! So is the correct website for EU zone "https://analytics.eu.amplitude.com/"? If so, should I recreate my organization and a project? I was using "https://analytics.amplitude.com/" website and see an API key but do not see any ways to create a EU-api key, project or organization

**Comment by bohan-amplitude** [comment]
@NuclearSnake  Correct. Need to create org and project on https://analytics.eu.amplitude.com/. The EU API key can be found under project setting on the EU website.
