### ISSUE TITLE
Support for dry run to prevent logging

### ISSUE THREAD

**Issue by smitp** [amplitude/Amplitude-Android#36]
Support for dry run to prevent data being sent to Amplitude. 

This should be helpful when testing or debugging applications. Google Analytics supports similar configuration. [Here](https://developers.google.com/analytics/devguides/collection/android/v3/advanced#testing)

**Comment by allanca** [comment]
Great idea. Thanks for the suggestions.

We recently added support for opting users out of tracking. You can use this feature to do what you're wanting here. Call ```Amplitude.getInstance().setOptOut(true)```.

I also just committed a change that will log a DEBUG message on each call to logEvent whether or not the event is logged to the server.
