### ISSUE TITLE
@Rajuahmed786 to Google account setting change anything to remove to vivo Odr and setting to recovery Atomaitic vivo v19 odr

### ISSUE THREAD

**Issue by Rajuahmed786** [amplitude/Amplitude-Android#365]
1  .546,;
2. .683,,;

**Comment by Rajuahmed786** [comment]
All recovered 2day only
Android to windows phone use

**Comment by justin-fiedler** [comment]
Hi @Rajuahmed786 thanks for using Amplitude. Can you please provide more details about this request? Thanks
