### ISSUE TITLE
Dex failures

### ISSUE THREAD

**Issue by f2prateek** [amplitude/Amplitude-Android#38]
We're running into issues with the 1.6.0 Amplitude JAR: `java.lang.IllegalArgumentException: already added: Lcom/amplitude/api/Amplitude;`. At first I thought it was an issue in our packaging, but running `dx` directly on the JAR fails as well.

https://cloudup.com/c1XWbzqkKd2

**Comment by f2prateek** [comment]
My bad, noticed this was fixed in 1.6.1

**Comment by allanca** [comment]
Thanks for the report. Unfortunately, 1.6.0 had a packaging error. Please try 1.6.1 and see if it fixes your issue.
