### ISSUE TITLE
NullPointerException occurred randomly.

### ISSUE THREAD

**Issue by visla-yewang** [amplitude/Amplitude-Android#380]
## Expected Behavior
No Exception should happen.

## Current Behavior
Exception java.lang.NullPointerException:
  at w2.a$d.r (Amplitude.kt:4)
  at sf.a.h (ContinuationImpl.kt:4)
  at ig.z0.run (DispatchedTask.kt:22)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)

## Possible Solution
N/A

## Steps to Reproduce
1. No Step, monitor on play store console, and several user meet the issue.

## Environment
- SDK Version: 1.4.6

**Comment by yuhao900914** [comment]
Hi @visla-yewang, 
Thanks for choosing Amplitude.
Are you using the [maintenance Android SDK](https://www.docs.developers.amplitude.com/data/sdks/android/) or [the latest Android SDK](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/)?  
- If you are using maintenance SDK, v1.4.6 is a super old version. We recommended you to upgrade the latest version or even upgrade to the[ latest android SDK.](https://www.docs.developers.amplitude.com/data/sdks/android/). The SDK provides more ways for debugging please check the `Troubleshooting and Debugging` section in the doc center. 
- If you are using the latest Android SDK. Please file another issue [here](https://github.com/amplitude/Amplitude-Kotlin). Without enough information, we are not able to reproduce the issue. Please try these [things](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#how-to-debug) to collect more information. Thanks.
