### ISSUE TITLE
Internal ANR

### ISSUE THREAD

**Issue by nseidm1** [amplitude/Amplitude-Android#395]
## Expected Behavior
 Be careful with main thread interactions

## Current Behavior
 Main thread ANRing

## Possible Solution
 Coroutines and/or oldschool threading

## Steps to Reproduce

Stack trace available

com.onesignal.common.modeling.Model.getBooleanProperty (unavailable)
com.onesignal.session.internal.session.SessionModel.isValid (SessionModel.kt:22)
com.onesignal.session.internal.session.impl.SessionService.onFocus (SessionService.kt:71)
com.onesignal.core.internal.application.impl.ApplicationService$handleFocus$1.invoke (ApplicationService.kt:387)
com.onesignal.core.internal.application.impl.ApplicationService$handleFocus$1.invoke (ApplicationService.kt:387)
com.onesignal.common.events.EventProducer.fire (EventProducer.kt:50)
com.onesignal.core.internal.application.impl.ApplicationService.handleFocus (ApplicationService.kt:387)
com.onesignal.core.internal.application.impl.ApplicationService.onActivityStarted (ApplicationService.kt:155)
android.app.Application.dispatchActivityStarted (Application.java:420)
android.app.Activity.dispatchActivityStarted (Activity.java:1452)
android.app.Activity.onStart (Activity.java:1981)
androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:344)
androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:251)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1543)
android.app.Activity.performStart (Activity.java:8682)
android.app.ActivityThread.handleStartActivity (ActivityThread.java:4219)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:221)
android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:201)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:173)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2584)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8810)
java.lang.reflect.Method.invoke (Native method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)

## Environment
Stack trace provided, version 1.16.1

**Comment by izaaz** [comment]
@nseidm1 Thank you for raising this issue. The stack trace you shared does not have any amplitude sdk referenced in it. Is this the right stack trace? Or am I missing something?

**Comment by nseidm1** [comment]
Apologies. Thank you for your time. Double checking.
