### ISSUE TITLE
ConcurrentModificationException occurs

### ISSUE THREAD

**Issue by Kanchan-tech1994** [amplitude/Amplitude-Android#405]
## Expected Behavior
App Must not crash.

## Current Behavior
Currently for multiple users app is getting crashed while sending event.

## Steps to Reproduce
We have updated our SDK as per your suggestion but still getting the same crash occurs.

SDK which we are currently using -> com.amplitude:analytics-android:1.+

Updating SDK doesn't resolve our issue.

Fatal Exception: java.util.ConcurrentModificationException
keyboard_arrow_up
java.util.HashMap$HashIterator.nextNode (HashMap.java:1603)
arrow_drop_down
com.amplitude.core.Amplitude.track$default (Amplitude.kt:175)
arrow_right
com. Dummy.analytics.client.AmplitudeSDK.logEvent (AmplitudeSDK.kt:106)
com. Dummy.utils.event.EventBuilder.build (EventBuilder.java:315)
com. Dummy.analytics.screenView.ScreenViewEvents.sendAmplitudeEvent (ScreenViewEvents.kt:173)
com. Dummy.analytics.screenView.ScreenViewEvents.send (ScreenViewEvents.kt:28)
com. Dummy.activity.BaseActivity.sendScreenViewEvent (BaseActivity.java:2603)
com. Dummy.activity.fragment.next_gen_home.NextGenHomeFragment.onViewCreated (NextGenHomeFragment.kt:387)
androidx.fragment.app.Fragment.performViewCreated (Fragment.java:3137)
arrow_drop_down
androidx.appcompat.app.AppCompatActivity.onStart (AppCompatActivity.java:251)
com.Dummy.activity.BaseActivity.onStart (BaseActivity.java:233)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1582)
arrow_drop_down
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:992)

## Environment
- SDK Version: 
   com.amplitude:analytics-android:1.16.8
   com.squareup.okhttp3:okhttp:4.9.0

<img width="430" alt="Screenshot 2024-11-05 at 4 14 43 PM" src="https://github.com/user-attachments/assets/88eea5d0-4e34-4a7a-bfec-bdcd7b0bf567">
<img width="527" alt="Screenshot 2024-11-05 at 4 15 33 PM" src="https://github.com/user-attachments/assets/df7cdeaf-e2f6-4a2a-a8f4-6571d17f4450">

**Comment by izaaz** [comment]
Hi @Kanchan-tech1994 - this SDK is no longer being maintained. Can you please use the new [Kotlin SDK](https://github.com/amplitude/Amplitude-Kotlin/) instead?

**Comment by Kanchan-tech1994** [comment]
Hi @izaaz ,

Thank you for your response.

As you can see, I am already using the Kotlin SDK (com.amplitude:analytics-android:1.+). Despite updating to the latest version of the Kotlin SDK, I am still encountering the same crash within the AmplitudeSDK.kt file, specifically at line 106.

Could you kindly assist in further investigating this issue?
