### ISSUE TITLE
Add listener for amplitude errors instead of logging via Android Log

### ISSUE THREAD

**Issue by niqo01** [amplitude/Amplitude-Android#47]
It would be great if you guys could add a listener for amplitude errors like :

```
    public interface Listener {
        void onError(AmplitudeException error);
    }
```

Amplitude sdk users would use it to either logs error via Android `Log` and/or report errors to a bug report tool like Crashlytics.

**Comment by niqo01** [comment]
Here is an example:
https://github.com/niqo01/Amplitude-Android/pull/3/files

**Comment by haoliu-amp** [comment]
Hello @niqo01 , what's the motivation for you to know the errors that Amplitude triggers?

Would it be enough to see it from the console logging?

**Comment by haoliu-amp** [comment]
Closing it for now
