### ISSUE TITLE
enableForegroundTracking method not available

### ISSUE THREAD

**Issue by muditklabs** [amplitude/Amplitude-Android#55]
Hi,

I am using sdk-1.7.0 for my android app and trying to enable foreground tracking for Android API level 14+ but the code is giving compilation error.

here is my code:

Build.gradle :
 
```compile 'com.amplitude:android-sdk:1.7.0'```

Java Code:

```java
Amplitude.getInstance().initialize(this, AMPLITUDE_API_KEY);
if (Build.VERSION.SDK_INT > 14) {
     Amplitude.getInstance().enableForegroundTracking(this);
}

**Comment by curtisliu** [comment]
The README in the master branch contains changes that haven't been released yet. Thus, enableForegroundTracking isn't present in the 1.7.0 release. You'll want to refer to the README in the tagged 1.7.0 release.
