### ISSUE TITLE
Amplitude artifact in mavencentral is incomplete

### ISSUE THREAD

**Issue by estornino** [amplitude/Amplitude-Android#59]
Hi,
I'm having an issue with the library if I define the dependencies using gradle.

I'm unable to import com.amplitude.api (not found) but I can use com.amplitude.security

If I just download the amplitude jar and add it to the Android Studio project, it works like a charm

**Comment by jtwigg** [comment]
Agreed. Its not functional.

**Comment by curtisliu** [comment]
We're aware of the broken jar in Maven. Thanks for reporting, will fix it shortly!

**Comment by djih** [comment]
v2.0.2 is fixed and now in Maven
