### ISSUE TITLE
Identify class is not found in the latest sdk

### ISSUE THREAD

**Issue by moehninhtwe** [amplitude/Amplitude-Android#65]
I would like to use the setOnce method belongs to Identify class. But I am not able to find it.

**Comment by djih** [comment]
Hi, those changes have not been released yet (https://github.com/amplitude/Amplitude-Android/blob/master/CHANGELOG.md#unreleased). We will release it as v2.1.0 either tomorrow or early next week. In the mean time you download the unreleased jar from here and it should have the identify class: https://github.com/amplitude/Amplitude-Android/blob/master/amplitude-android-2.0.4-with-dependencies.jar

**Comment by djih** [comment]
FYI v2.1.0 is released, and you can now start using the Identify class: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.1.0

**Comment by moehninhtwe** [comment]
Thank you very much!
On 6 Oct 2015 05:41, "djih" <notifications@github.com> wrote:

> FYI v2.1.0 is released, and you can now start using the Identify class:
> https://github.com/amplitude/Amplitude-Android/releases/tag/v2.1.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amplitude/Amplitude-Android/issues/65#issuecomment-145676456>
> .
>

-- 


NOTE: Privileged/Confidential Information may be contained in this message. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message and kindly notify the sender by reply email. All opinions, conclusions and other information expressed in this message not of an official nature shall not be deemed as given or endorsed by 701Search Pte Ltd or any of its subsidiaries unless otherwise indicated by an authorised representative independent of this message.
701Search Pte Ltd
Regn No. 200613507R
