### ISSUE TITLE
Remove references to Apache HTTPClient classes

### ISSUE THREAD

**Issue by benjamin-bader** [amplitude/Amplitude-Android#66]
Android M has removed HTTPClient entirely.  Amplitude has switched to OkHttp for making posts, but the client still references Apache - spuriously, from what I can tell.

In any event, the reference means that Amplitude can't be used on M without also including the legacy Apache stuff manually.

As far as I can tell, the fix is one line - replace `org.apache.http.conn.HttpHostConnectException` with `java.net.ConnectException` in `AmplitudeClient#makeEventUploadPostRequest`.

**Comment by djih** [comment]
Thanks for bringing this to our attention. We will make the change for our next release.

**Comment by benjamin-bader** [comment]
Just saw the commit - thanks!

**Comment by djih** [comment]
Updated here: https://github.com/amplitude/Amplitude-Android/commit/87f7abd73ead460291ae41a3c47be1faf35a5f49, will be in next release

**Comment by djih** [comment]
This is released with [v2.2.0](https://github.com/amplitude/Amplitude-Android/releases/tag/v2.2.0), might take a few hours to appear on Maven Central
