### ISSUE TITLE
update to new OKhttp version

### ISSUE THREAD

**Issue by alosdev** [amplitude/Amplitude-Android#73]
It would be nice, that the amplitude android sdk updates to the new okhttp version 3.0.1

**Comment by djih** [comment]
Hi @alosdev , is there some specific functionality in v3.0.1 that you would like? Or is that the version that you are using for your app as well?

**Comment by alosdev** [comment]
Currently I migrated all my Code to okhttp Version 3 and don't want these both parallel because of method count and size. It would be nice to have a pluggable network stack like in Glide, where we can use different one or create our own.

**Comment by djih** [comment]
@alosdev : I have code ready for v3.0.1 upgrade: https://github.com/amplitude/Amplitude-Android/compare/upgrade_okhttp_v3?expand=1, just need to do a little more testing. It should be good to go in the next release unless otherwise noted
