### ISSUE TITLE
Daily Active User Data issue

### ISSUE THREAD

**Issue by Euhow** [amplitude/Amplitude-Android#74]
Hi,

We recently noticed that the daily active user has dropped 20% but we also have Flurry daily active users tracking which represent that our daily active user is growing, can you please tell us how do you identify if a user is 'active' in one day? Or point us some way to find the reason?

Thank you.

**Comment by djih** [comment]
@Euhow we define an active user on a particular day as someone who has logged an event on that day. This means that someone who uses your app but doesn't log any events would not appear as an active user. 

You can have the SDK automatically log start and end session events, which more or less correlate to when the user opens your app. This will allow those users to appear as active, even if they don't log any events that you have instrumented. More info here: https://github.com/amplitude/Amplitude-Android/tree/v2.5.0#tracking-sessions

You would want to have both `enableForegroundTracking` and `trackSessionEvents` enabled.

Some helpful definitions: https://amplitude.zendesk.com/hc/en-us/articles/204620508-Appendix-Helpful-Definitions
