### ISSUE TITLE
OkHttp 3 support

### ISSUE THREAD

**Issue by niqo01** [amplitude/Amplitude-Android#79]
Amplitude support for OkHttp version 3 should include sharing the OkHttp instance as parameter as recommended in OkHttp 3 changelog.

```
There is no longer a global singleton connection pool. In OkHttp 2.x, all OkHttpClient instances shared a common connection pool by default. In OkHttp 3.x, each new OkHttpClient gets its own private connection pool. Applications should avoid creating many connection pools as doing so prevents connection reuse. Each connection pool holds its own set of connections alive so applications that have many pools also risk exhausting memory!

The best practice in OkHttp 3 is to create a single OkHttpClient instance and share it throughout the application. Requests that needs a customized client should call OkHttpClient.newBuilder() on that shared instance. This allows customization without the drawbacks of separate connection pools.
```

**Comment by djih** [comment]
@niqo01 do you mean like this: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L115? We create an instance and save it to the AmplitudeClient instance. 

Here is where we pass the client to the function making the request: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L824

**Comment by djih** [comment]
Hmm maybe all of the AmplitudeClients together should share an instance as well

**Comment by niqo01** [comment]
Yes I was referencing the line 115 in AmplitudeClient. You could create one if null or use`client.newBuilder()` if the library's user give an instance of Okhttp.

**Comment by haoliu-amp** [comment]
We will support it very soon.
