### ISSUE TITLE
Nullpointer Exception in initialization

### ISSUE THREAD

**Issue by ravimittal99** [amplitude/Amplitude-Android#95]
> java.lang.NullPointerException
> com.amplitude.api.AmplitudeClient.getSharedPreferencesName(AmplitudeClient.java:1054)
> com.amplitude.api.AmplitudeClient.getLastEventTime(AmplitudeClient.java:438)
> com.amplitude.api.AmplitudeClient.isWithinMinTimeBetweenSessions(AmplitudeClient.java:534)
> com.amplitude.api.AmplitudeClient.startNewSessionIfNeeded(AmplitudeClient.java:498)
> com.amplitude.api.AmplitudeClient.logEvent(AmplitudeClient.java:333)
> com.amplitude.api.AmplitudeClient$2.run(AmplitudeClient.java:313)
> android.os.Handler.handleCallback(Handler.java:808)
> android.os.Handler.dispatchMessage(Handler.java:103)
> android.os.Looper.loop(Looper.java:193)
> android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by djih** [comment]
@ravimittal99 what version are you using? It looks like you are calling logEvent before you call initialize with the apiKey and context, which is why it's NPE.

**Comment by ravimittal99** [comment]
Version 2.3.0. I don't see this issue anymore after updating to the latest version.
